# Generated by Django 5.2.1 on 2025-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspot_app', '0002_productmodel_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
