# Generated by Django 5.2.1 on 2025-05-23 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techspot_app', '0004_alter_productmodel_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItemModel',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
    ]
