# Generated by Django 5.2.1 on 2025-05-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspot_app', '0005_rename_orderitem_orderitemmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='techspot_app.usermodel'),
        ),
    ]
