# Generated by Django 5.2.1 on 2025-06-09 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techspot_app', '0007_usermodel_groups_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
