# Generated by Django 5.2.1 on 2025-06-17 06:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techspot_app', '0010_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
