# Generated by Django 5.1 on 2024-08-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
