# Generated by Django 5.1 on 2024-08-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0002_rename_categories_categorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
