# Generated by Django 5.1 on 2024-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0005_alter_category_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
