# Generated by Django 5.1 on 2024-08-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0007_alter_category_category_name_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='category',
            new_name='sub_category',
        ),
    ]
