# Generated by Django 5.1 on 2024-08-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0008_rename_category_sub_category_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_category',
            new_name='category',
        ),
    ]
