# Generated by Django 5.1 on 2024-09-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0009_rename_sub_category_sub_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/images/default_images.png', upload_to='static/images/slider')),
            ],
        ),
    ]
