# Generated by Django 5.1 on 2024-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0011_remove_imageslider_image_imageslider_slider_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageslider',
            name='slider_name',
        ),
        migrations.AddField(
            model_name='imageslider',
            name='image',
            field=models.ImageField(default='static/images/default_images.png', upload_to='static/images/slider'),
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
