# Generated by Django 5.1 on 2024-09-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0012_remove_imageslider_slider_name_imageslider_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslider',
            name='image',
            field=models.ImageField(default='static\\images\\default_image.png', upload_to='images/slider'),
        ),
    ]
