# Generated by Django 5.1 on 2024-09-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0013_alter_imageslider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslider',
            name='image',
            field=models.ImageField(upload_to='static/images/slider'),
        ),
    ]
