# Generated by Django 5.1 on 2024-09-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0014_alter_imageslider_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imageSlider',
            new_name='image_Slider',
        ),
    ]
