# Generated by Django 5.1 on 2024-09-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0015_rename_imageslider_image_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_slider',
            name='image',
            field=models.ImageField(upload_to='static/images/slider/'),
        ),
    ]
