# Generated by Django 5.1 on 2024-09-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0020_alter_image_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to='category_image/'),
        ),
    ]
