# Generated by Django 5.1 on 2024-09-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0021_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('product_description', models.CharField(default='', max_length=200)),
                ('product_price', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
