# Generated by Django 5.1 on 2024-09-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0023_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='productImage/'),
        ),
    ]
