# Generated by Django 5.1 on 2024-09-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0024_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='productSubCategory', to='nep_app.sub_category'),
        ),
    ]
