# Generated by Django 5.1 on 2024-09-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0029_product_pro_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_sub_category',
        ),
    ]
