# Generated by Django 5.1 on 2024-09-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0031_product_pro_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image_url',
            field=models.ImageField(default='', upload_to='category_image/'),
        ),
        migrations.AddField(
            model_name='image_slider',
            name='image_url',
            field=models.ImageField(default='', upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='image_slider',
            name='image',
            field=models.ImageField(default='', upload_to='slider/'),
        ),
    ]
