# Generated by Django 5.1 on 2024-09-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0033_alter_category_category_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='', upload_to='category_image/'),
        ),
    ]
