# Generated by Django 5.1 on 2024-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0034_alter_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='category_imageUrl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='image_slider',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
