# Generated by Django 5.1 on 2024-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0035_remove_category_category_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_imageUrl',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image_slider',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
