# Generated by Django 5.1 on 2024-09-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0036_alter_category_category_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_imageUrl',
        ),
        migrations.RemoveField(
            model_name='image_slider',
            name='image_url',
        ),
    ]
