# Generated by Django 5.1 on 2024-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0038_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
