# Generated by Django 5.1 on 2024-09-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0040_cartitem_quantity_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_url',
        ),
    ]
