# Generated by Django 5.1 on 2024-11-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0042_product_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image_left', models.ImageField(default='', upload_to='header/')),
                ('header_image_right', models.ImageField(default='', upload_to='header/')),
            ],
        ),
    ]
