# Generated by Django 5.1 on 2024-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0043_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_image_left',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
        migrations.AlterField(
            model_name='header',
            name='header_image_right',
            field=models.ImageField(blank=True, null=True, upload_to='header/'),
        ),
    ]
