# Generated by Django 5.1 on 2025-01-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0045_socialmedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='OtherDetail',
        ),
    ]
