# Generated by Django 5.1 on 2025-01-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0046_rename_socialmedia_otherdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdetail',
            name='sm_icon',
        ),
    ]
