# Generated by Django 5.1.5 on 2025-01-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nep_app', '0048_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
